/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as FreeQuoteRouteImport } from './routes/free-quote'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ServicesTreeBrushRemovalRouteImport } from './routes/services/tree-brush-removal'
import { Route as ServicesResidentialWireHouseCleaningRouteImport } from './routes/services/residential-wire-house-cleaning'
import { Route as ServicesOfficeCommercialCleaningRouteImport } from './routes/services/office-commercial-cleaning'
import { Route as ServicesLawnMowingRouteImport } from './routes/services/lawn-mowing'
import { Route as ServicesLandscapingRouteImport } from './routes/services/landscaping'
import { Route as ServicesGravelDirtWorkRouteImport } from './routes/services/gravel-dirt-work'
import { Route as DashboardLoginRouteImport } from './routes/dashboard/login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeQuoteRoute = FreeQuoteRouteImport.update({
  id: '/free-quote',
  path: '/free-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTreeBrushRemovalRoute =
  ServicesTreeBrushRemovalRouteImport.update({
    id: '/tree-brush-removal',
    path: '/tree-brush-removal',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesResidentialWireHouseCleaningRoute =
  ServicesResidentialWireHouseCleaningRouteImport.update({
    id: '/residential-wire-house-cleaning',
    path: '/residential-wire-house-cleaning',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesOfficeCommercialCleaningRoute =
  ServicesOfficeCommercialCleaningRouteImport.update({
    id: '/office-commercial-cleaning',
    path: '/office-commercial-cleaning',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesLawnMowingRoute = ServicesLawnMowingRouteImport.update({
  id: '/lawn-mowing',
  path: '/lawn-mowing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLandscapingRoute = ServicesLandscapingRouteImport.update({
  id: '/landscaping',
  path: '/landscaping',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGravelDirtWorkRoute = ServicesGravelDirtWorkRouteImport.update({
  id: '/gravel-dirt-work',
  path: '/gravel-dirt-work',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/free-quote': typeof FreeQuoteRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/gravel-dirt-work': typeof ServicesGravelDirtWorkRoute
  '/services/landscaping': typeof ServicesLandscapingRoute
  '/services/lawn-mowing': typeof ServicesLawnMowingRoute
  '/services/office-commercial-cleaning': typeof ServicesOfficeCommercialCleaningRoute
  '/services/residential-wire-house-cleaning': typeof ServicesResidentialWireHouseCleaningRoute
  '/services/tree-brush-removal': typeof ServicesTreeBrushRemovalRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/free-quote': typeof FreeQuoteRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/gravel-dirt-work': typeof ServicesGravelDirtWorkRoute
  '/services/landscaping': typeof ServicesLandscapingRoute
  '/services/lawn-mowing': typeof ServicesLawnMowingRoute
  '/services/office-commercial-cleaning': typeof ServicesOfficeCommercialCleaningRoute
  '/services/residential-wire-house-cleaning': typeof ServicesResidentialWireHouseCleaningRoute
  '/services/tree-brush-removal': typeof ServicesTreeBrushRemovalRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/free-quote': typeof FreeQuoteRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/gravel-dirt-work': typeof ServicesGravelDirtWorkRoute
  '/services/landscaping': typeof ServicesLandscapingRoute
  '/services/lawn-mowing': typeof ServicesLawnMowingRoute
  '/services/office-commercial-cleaning': typeof ServicesOfficeCommercialCleaningRoute
  '/services/residential-wire-house-cleaning': typeof ServicesResidentialWireHouseCleaningRoute
  '/services/tree-brush-removal': typeof ServicesTreeBrushRemovalRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/free-quote'
    | '/projects'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/services/gravel-dirt-work'
    | '/services/landscaping'
    | '/services/lawn-mowing'
    | '/services/office-commercial-cleaning'
    | '/services/residential-wire-house-cleaning'
    | '/services/tree-brush-removal'
    | '/dashboard/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/free-quote'
    | '/projects'
    | '/reviews'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/services/gravel-dirt-work'
    | '/services/landscaping'
    | '/services/lawn-mowing'
    | '/services/office-commercial-cleaning'
    | '/services/residential-wire-house-cleaning'
    | '/services/tree-brush-removal'
    | '/dashboard'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/free-quote'
    | '/projects'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/services/gravel-dirt-work'
    | '/services/landscaping'
    | '/services/lawn-mowing'
    | '/services/office-commercial-cleaning'
    | '/services/residential-wire-house-cleaning'
    | '/services/tree-brush-removal'
    | '/dashboard/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FreeQuoteRoute: typeof FreeQuoteRoute
  ProjectsRoute: typeof ProjectsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-quote': {
      id: '/free-quote'
      path: '/free-quote'
      fullPath: '/free-quote'
      preLoaderRoute: typeof FreeQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/tree-brush-removal': {
      id: '/services/tree-brush-removal'
      path: '/tree-brush-removal'
      fullPath: '/services/tree-brush-removal'
      preLoaderRoute: typeof ServicesTreeBrushRemovalRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/residential-wire-house-cleaning': {
      id: '/services/residential-wire-house-cleaning'
      path: '/residential-wire-house-cleaning'
      fullPath: '/services/residential-wire-house-cleaning'
      preLoaderRoute: typeof ServicesResidentialWireHouseCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/office-commercial-cleaning': {
      id: '/services/office-commercial-cleaning'
      path: '/office-commercial-cleaning'
      fullPath: '/services/office-commercial-cleaning'
      preLoaderRoute: typeof ServicesOfficeCommercialCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/lawn-mowing': {
      id: '/services/lawn-mowing'
      path: '/lawn-mowing'
      fullPath: '/services/lawn-mowing'
      preLoaderRoute: typeof ServicesLawnMowingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/landscaping': {
      id: '/services/landscaping'
      path: '/landscaping'
      fullPath: '/services/landscaping'
      preLoaderRoute: typeof ServicesLandscapingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/gravel-dirt-work': {
      id: '/services/gravel-dirt-work'
      path: '/gravel-dirt-work'
      fullPath: '/services/gravel-dirt-work'
      preLoaderRoute: typeof ServicesGravelDirtWorkRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesGravelDirtWorkRoute: typeof ServicesGravelDirtWorkRoute
  ServicesLandscapingRoute: typeof ServicesLandscapingRoute
  ServicesLawnMowingRoute: typeof ServicesLawnMowingRoute
  ServicesOfficeCommercialCleaningRoute: typeof ServicesOfficeCommercialCleaningRoute
  ServicesResidentialWireHouseCleaningRoute: typeof ServicesResidentialWireHouseCleaningRoute
  ServicesTreeBrushRemovalRoute: typeof ServicesTreeBrushRemovalRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesGravelDirtWorkRoute: ServicesGravelDirtWorkRoute,
  ServicesLandscapingRoute: ServicesLandscapingRoute,
  ServicesLawnMowingRoute: ServicesLawnMowingRoute,
  ServicesOfficeCommercialCleaningRoute: ServicesOfficeCommercialCleaningRoute,
  ServicesResidentialWireHouseCleaningRoute:
    ServicesResidentialWireHouseCleaningRoute,
  ServicesTreeBrushRemovalRoute: ServicesTreeBrushRemovalRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FreeQuoteRoute: FreeQuoteRoute,
  ProjectsRoute: ProjectsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
